{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "2f32d9f2-6f78-462f-8f80-e5993e1da1c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from pyzbar.pyzbar import decode\n",
    "import pandas as pd\n",
    "from datetime import date\n",
    "from dateutil.relativedelta import relativedelta\n",
    "import qrcode\n",
    "from PIL import Image\n",
    "from io import BytesIO\n",
    "import plotly.express as px\n",
    "import numpy as np\n",
    "import os\n",
    "import time\n",
    "\n",
    "class HulkGymQRSystem:\n",
    "    def __init__(self):\n",
    "        st.set_page_config(page_title=\"HULK GYM PRO\", layout=\"wide\", page_icon=\"💪\")\n",
    "        self.excel_path = \"gym_data.xlsx\"\n",
    "        self.load_data()\n",
    "        self.setup_ui()\n",
    "    \n",
    "    def load_data(self):\n",
    "        if os.path.exists(self.excel_path):\n",
    "            self.df = pd.read_excel(self.excel_path)\n",
    "            date_cols = ['Start Date', 'End Date']\n",
    "            for col in date_cols:\n",
    "                if col in self.df.columns:\n",
    "                    self.df[col] = pd.to_datetime(self.df[col]).dt.date\n",
    "        else:\n",
    "            self.df = pd.DataFrame(columns=[\n",
    "                'QR Code', 'Count', 'Start Date', \n",
    "                'End Date', \"Paid\", \"remaining\", \"Phone\", \"Membership Type\"\n",
    "            ])\n",
    "    \n",
    "    def save_data(self):\n",
    "        df_to_save = self.df.copy()\n",
    "        date_cols = ['Start Date', 'End Date']\n",
    "        for col in date_cols:\n",
    "            if col in df_to_save.columns:\n",
    "                df_to_save[col] = df_to_save[col].astype(str)\n",
    "        df_to_save.to_excel(self.excel_path, index=False)\n",
    "    \n",
    "    def setup_ui(self):\n",
    "        st.markdown(\"\"\"\n",
    "        <style>\n",
    "            .welcome-message {\n",
    "                font-size: 42px !important;\n",
    "                font-weight: bold !important;\n",
    "                color: #FFD700 !important;\n",
    "                text-align: center;\n",
    "                margin: 20px 0;\n",
    "                text-shadow: 2px 2px 4px #000;\n",
    "            }\n",
    "            .stats-card {\n",
    "                background: linear-gradient(135deg, #1e1e1e, #2a2a2a);\n",
    "                border-radius: 10px;\n",
    "                padding: 15px;\n",
    "                box-shadow: 0 4px 8px rgba(0,0,0,0.2);\n",
    "                text-align: center;\n",
    "            }\n",
    "            .stApp {\n",
    "                background-color: #121212;\n",
    "                color: white;\n",
    "            }\n",
    "            .stCameraInput > div {\n",
    "                border-radius: 10px;\n",
    "                overflow: hidden;\n",
    "            }\n",
    "        </style>\n",
    "        \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        st.title(\"🏋️ HULK GYM PRO\")\n",
    "        tabs = st.tabs([\"📷 Scan Member\", \"✨ Create Member\", \"🔄 Renew Subscription\", \"📊 Analytics\"])\n",
    "        \n",
    "        with tabs[0]:\n",
    "            self.scan_qr_tab()\n",
    "        with tabs[1]:\n",
    "            self.create_qr_tab()\n",
    "        with tabs[2]:\n",
    "            self.renew_tab()\n",
    "        with tabs[3]:\n",
    "            self.view_analytics_tab()\n",
    "    \n",
    "    def scan_qr_tab(self):\n",
    "        st.header(\"🔍 Member Check-In\")\n",
    "        welcome_placeholder = st.empty()\n",
    "        \n",
    "        # استخدام st.camera_input بدلاً من cv2.VideoCapture\n",
    "        img_file = st.camera_input(\"Scan QR Code\", key=\"qr_scanner\")\n",
    "        \n",
    "        if img_file is not None:\n",
    "            try:\n",
    "                img = Image.open(img_file)\n",
    "                frame = np.array(img)\n",
    "                qr_codes = decode(frame)\n",
    "                \n",
    "                if qr_codes:\n",
    "                    for qr in qr_codes:\n",
    "                        qr_data = qr.data.decode('utf-8').strip()\n",
    "                        self.process_qr_code(qr_data, welcome_placeholder)\n",
    "            except Exception as e:\n",
    "                st.error(f\"Error scanning QR: {e}\")\n",
    "    \n",
    "    def process_qr_code(self, qr_data, welcome_placeholder):\n",
    "        if qr_data in self.df['QR Code'].values:\n",
    "            user_row = self.df[self.df['QR Code'] == qr_data].iloc[0]\n",
    "            end_date = user_row['End Date']\n",
    "            \n",
    "            if date.today() <= end_date:\n",
    "                welcome_html = f\"\"\"\n",
    "                <div class='welcome-message'>\n",
    "                    <div style='font-size: 48px;'>👋 Welcome</div>\n",
    "                    <div style='font-size: 56px;'>{qr_data}</div>\n",
    "                    <div style='font-size: 24px; margin-top: 20px;'>\n",
    "                        Valid until: <span style='color: #4CAF50;'>{end_date.strftime(\"%Y-%m-%d\")}</span>\n",
    "                    </div>\n",
    "                </div>\n",
    "                \"\"\"\n",
    "                welcome_placeholder.markdown(welcome_html, unsafe_allow_html=True)\n",
    "                self.df.loc[self.df['QR Code'] == qr_data, 'Count'] += 1\n",
    "                self.save_data()\n",
    "            else:\n",
    "                welcome_placeholder.error(\"❌ Subscription has expired\")\n",
    "        else:\n",
    "            welcome_placeholder.error(\"❌ Invalid QR Code\")\n",
    "    \n",
    "    def create_qr_tab(self):\n",
    "        st.header(\"✨ Create New Member\")\n",
    "        \n",
    "        if 'form_submitted' not in st.session_state:\n",
    "            st.session_state.form_submitted = False\n",
    "            st.session_state.form_data = {}\n",
    "        \n",
    "        with st.form(\"create_form\"):\n",
    "            col1, col2 = st.columns(2)\n",
    "            \n",
    "            with col1:\n",
    "                user_name = st.text_input(\"Member Name\", placeholder=\"Enter full name\")\n",
    "                phone = st.text_input(\"Phone Number\", placeholder=\"01012345678\")\n",
    "                membership_type = st.selectbox(\"Membership Type\", [\"Regular\", \"Premium\", \"VIP\"])\n",
    "            \n",
    "            with col2:\n",
    "                months = st.radio(\"Subscription Period\", [1, 3, 6, 12], \n",
    "                                 format_func=lambda x: f\"{x} Month{'s' if x > 1 else ''}\")\n",
    "                paid = st.number_input(\"Amount Paid\", min_value=0, value=300)\n",
    "                remaining = st.number_input(\"Remaining Amount\", min_value=0, value=0)\n",
    "            \n",
    "            if st.form_submit_button(\"Generate Membership\"):\n",
    "                if user_name:\n",
    "                    st.session_state.form_submitted = True\n",
    "                    st.session_state.form_data = {\n",
    "                        'user_name': user_name,\n",
    "                        'phone': phone,\n",
    "                        'membership_type': membership_type,\n",
    "                        'months': months,\n",
    "                        'paid': paid,\n",
    "                        'remaining': remaining\n",
    "                    }\n",
    "                else:\n",
    "                    st.error(\"Please enter member name\")\n",
    "        \n",
    "        if st.session_state.get('form_submitted', False):\n",
    "            form_data = st.session_state.form_data\n",
    "            qr_image = self.create_member(\n",
    "                form_data['user_name'],\n",
    "                form_data['phone'],\n",
    "                form_data['membership_type'],\n",
    "                form_data['months'],\n",
    "                form_data['paid'],\n",
    "                form_data['remaining']\n",
    "            )\n",
    "            \n",
    "            st.download_button(\n",
    "                label=\"⬇️ Download QR Code\",\n",
    "                data=qr_image,\n",
    "                file_name=f\"HULK_GYM_{form_data['user_name']}.png\",\n",
    "                mime=\"image/png\"\n",
    "            )\n",
    "    \n",
    "    def create_member(self, user_name, phone, membership_type, months, paid, remaining):\n",
    "        start_date = date.today()\n",
    "        end_date = start_date + relativedelta(months=months)\n",
    "        \n",
    "        qr = qrcode.QRCode(version=1, box_size=10, border=4)\n",
    "        qr.add_data(user_name)\n",
    "        qr.make(fit=True)\n",
    "        qr_img = qr.make_image(fill_color=\"black\", back_color=\"white\")\n",
    "        \n",
    "        img_bytes = BytesIO()\n",
    "        qr_img.save(img_bytes, format=\"PNG\")\n",
    "        img_bytes.seek(0)\n",
    "        \n",
    "        new_row = pd.DataFrame({\n",
    "            'QR Code': [user_name],\n",
    "            'Count': [0],\n",
    "            'Start Date': [start_date],\n",
    "            'End Date': [end_date],\n",
    "            'Paid': [paid],\n",
    "            'remaining': [remaining],\n",
    "            'Phone': [phone],\n",
    "            'Membership Type': [membership_type]\n",
    "        })\n",
    "        self.df = pd.concat([self.df, new_row], ignore_index=True)\n",
    "        self.save_data()\n",
    "        \n",
    "        st.success(\"🎉 Membership created successfully!\")\n",
    "        \n",
    "        col1, col2 = st.columns(2)\n",
    "        with col1:\n",
    "            st.image(img_bytes, caption=f\"QR Code for {user_name}\", width=300)\n",
    "        \n",
    "        with col2:\n",
    "            st.markdown(f\"\"\"\n",
    "            ### Member Details\n",
    "            - **Name**: {user_name}\n",
    "            - **Phone**: {phone}\n",
    "            - **Membership Type**: {membership_type}\n",
    "            - **Start Date**: {start_date}\n",
    "            - **End Date**: {end_date}\n",
    "            - **Paid**: {paid} EGP\n",
    "            - **Remaining**: {remaining} EGP\n",
    "            \"\"\")\n",
    "        \n",
    "        return img_bytes.getvalue()\n",
    "    \n",
    "    def renew_tab(self):\n",
    "        st.header(\"🔄 Renew Membership\")\n",
    "        \n",
    "        if not self.df.empty:\n",
    "            member = st.selectbox(\"Select Member\", self.df['QR Code'].unique())\n",
    "            \n",
    "            if member:\n",
    "                user_row = self.df[self.df['QR Code'] == member].iloc[0]\n",
    "                current_end = user_row['End Date']\n",
    "                \n",
    "                st.markdown(f\"\"\"\n",
    "                ### Current Membership Details\n",
    "                - **Member**: {member}\n",
    "                - **Phone**: {user_row.get('Phone', 'N/A')}\n",
    "                - **Membership Type**: {user_row.get('Membership Type', 'Regular')}\n",
    "                - **Current End Date**: {current_end}\n",
    "                - **Check-ins**: {user_row['Count']}\n",
    "                - **Paid Amount**: {user_row['Paid']} EGP\n",
    "                - **Remaining Amount**: {user_row['remaining']} EGP\n",
    "                \"\"\")\n",
    "                \n",
    "                with st.form(\"renew_form\"):\n",
    "                    months = st.radio(\"Renewal Period\", [1, 3, 6, 12], \n",
    "                                     format_func=lambda x: f\"{x} Month{'s' if x > 1 else ''}\")\n",
    "                    \n",
    "                    col1, col2 = st.columns(2)\n",
    "                    with col1:\n",
    "                        paid = st.number_input(\"Amount Paid\", min_value=0, value=int(user_row['Paid']))\n",
    "                    with col2:\n",
    "                        remaining = st.number_input(\"Remaining Amount\", min_value=0, value=int(user_row['remaining']))\n",
    "                    \n",
    "                    if st.form_submit_button(\"💳 Process Renewal\"):\n",
    "                        new_end_date = max(date.today(), current_end) + relativedelta(months=months)\n",
    "                        \n",
    "                        self.df.loc[self.df['QR Code'] == member, 'End Date'] = new_end_date\n",
    "                        self.df.loc[self.df['QR Code'] == member, 'Paid'] = paid\n",
    "                        self.df.loc[self.df['QR Code'] == member, 'remaining'] = remaining\n",
    "                        self.save_data()\n",
    "                        \n",
    "                        st.success(f\"\"\"\n",
    "                        ✅ Membership for {member} renewed successfully!\n",
    "                        New end date: {new_end_date}\n",
    "                        \"\"\")\n",
    "        else:\n",
    "            st.warning(\"No members found in database\")\n",
    "    \n",
    "    def view_analytics_tab(self):\n",
    "        st.header(\"📊 Gym Analytics Dashboard\")\n",
    "        \n",
    "        if not self.df.empty:\n",
    "            st.subheader(\"📈 Key Metrics\")\n",
    "            self.display_stats_cards()\n",
    "            \n",
    "            st.subheader(\"📅 Membership Analytics\")\n",
    "            tab1, tab2, tab3 = st.tabs([\"Subscriptions\", \"Check-ins\", \"Payments\"])\n",
    "            \n",
    "            with tab1:\n",
    "                self.plot_subscriptions_chart()\n",
    "            \n",
    "            with tab2:\n",
    "                self.plot_checkins_chart()\n",
    "            \n",
    "            with tab3:\n",
    "                self.plot_payments_chart()\n",
    "            \n",
    "            st.subheader(\"👥 Members Data\")\n",
    "            st.dataframe(self.df, use_container_width=True)\n",
    "            \n",
    "            st.download_button(\n",
    "                label=\"📤 Export Data to Excel\",\n",
    "                data=self.df.to_csv(index=False).encode('utf-8'),\n",
    "                file_name=\"hulk_gym_members.csv\",\n",
    "                mime=\"text/csv\"\n",
    "            )\n",
    "        else:\n",
    "            st.warning(\"No data available for analytics\")\n",
    "    \n",
    "    def display_stats_cards(self):\n",
    "        total_members = len(self.df)\n",
    "        active_members = len(self.df[self.df['End Date'] >= date.today()])\n",
    "        expired_members = total_members - active_members\n",
    "        total_revenue = self.df['Paid'].sum()\n",
    "        avg_checkins = self.df['Count'].mean()\n",
    "        \n",
    "        cols = st.columns(5)\n",
    "        \n",
    "        with cols[0]:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class='stats-card'>\n",
    "                <div class='stats-value'>{total_members}</div>\n",
    "                <div class='stats-label'>Total Members</div>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        with cols[1]:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class='stats-card'>\n",
    "                <div class='stats-value' style='color: #4CAF50;'>{active_members}</div>\n",
    "                <div class='stats-label'>Active Members</div>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        with cols[2]:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class='stats-card'>\n",
    "                <div class='stats-value' style='color: #F44336;'>{expired_members}</div>\n",
    "                <div class='stats-label'>Expired Members</div>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        with cols[3]:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class='stats-card'>\n",
    "                <div class='stats-value' style='color: #FFD700;'>{total_revenue} EGP</div>\n",
    "                <div class='stats-label'>Total Revenue</div>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "        \n",
    "        with cols[4]:\n",
    "            st.markdown(f\"\"\"\n",
    "            <div class='stats-card'>\n",
    "                <div class='stats-value'>{avg_checkins:.1f}</div>\n",
    "                <div class='stats-label'>Avg Check-ins</div>\n",
    "            </div>\n",
    "            \"\"\", unsafe_allow_html=True)\n",
    "    \n",
    "    def plot_subscriptions_chart(self):\n",
    "        df = self.df.copy()\n",
    "        df['Month'] = pd.to_datetime(df['Start Date']).dt.to_period('M')\n",
    "        monthly_data = df.groupby('Month').size().reset_index(name='Count')\n",
    "        monthly_data['Month'] = monthly_data['Month'].astype(str)\n",
    "        \n",
    "        fig = px.bar(monthly_data, x='Month', y='Count', \n",
    "                     title=\"New Memberships by Month\",\n",
    "                     color='Count',\n",
    "                     color_continuous_scale='thermal')\n",
    "        fig.update_layout(plot_bgcolor='#1e1e1e', paper_bgcolor='#1e1e1e',\n",
    "                         font=dict(color='white'))\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    def plot_checkins_chart(self):\n",
    "        df = self.df.sort_values('Count', ascending=False).head(10)\n",
    "        \n",
    "        fig = px.bar(df, x='QR Code', y='Count', \n",
    "                     title=\"Top Members by Check-ins\",\n",
    "                     color='Count',\n",
    "                     color_continuous_scale='viridis')\n",
    "        fig.update_layout(plot_bgcolor='#1e1e1e', paper_bgcolor='#1e1e1e',\n",
    "                         font=dict(color='white'))\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "    \n",
    "    def plot_payments_chart(self):\n",
    "        df = self.df.copy()\n",
    "        df['Payment Status'] = df.apply(lambda x: \"Paid in Full\" if x['remaining'] == 0 else \"Partial Payment\", axis=1)\n",
    "        \n",
    "        fig = px.pie(df, names='Payment Status', \n",
    "                     title=\"Payment Status Distribution\",\n",
    "                     hole=0.4,\n",
    "                     color='Payment Status',\n",
    "                     color_discrete_map={'Paid in Full':'#4CAF50', 'Partial Payment':'#FFA500'})\n",
    "        fig.update_layout(plot_bgcolor='#1e1e1e', paper_bgcolor='#1e1e1e',\n",
    "                         font=dict(color='white'))\n",
    "        st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app = HulkGymQRSystem()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "81d60cb8-ed04-4e3e-8dbf-9c39aa274242",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
